---
- hosts: all
  become: yes
  tasks:

    - name: Build hosts file
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
      when: hostvars[item].ansible_eth1.ipv4.address is defined
      with_items: groups['all']

  roles:
    - { role: jpnewman.locale-timezone, tags: ["init"] }
    - { role: jpnewman.common, tags: ["init"] }
    - { role: jpnewman.java, tags: ["init"] }

- hosts: jenkins-server
  tags: ["jenkins_server"]
  become: yes
  roles:
    - { role: geerlingguy.security, tags: ['security'] }
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.git, tags: ['git'] }
    - { role: jpnewman.jenkins, tags: ["jenkins"] }
    - { role: jpnewman.nginx, tags: ["nginx"] }
