---
nginx_remove_default_vhost: true

nginx_vhost_filename: jenkins

nginx_vhost_available_path: /etc/nginx/sites-available
nginx_vhost_path: /etc/nginx/sites-enabled

www_redirect: false
listen_ports:
  - 80

host_aliases: []
max_upload_size: "1024m"
host_name: localhost
redirect_http: true

ssl_enabled: true
ssl_listen_ports:
  - 443

ssl_ca_local_path: ""
ssl_ca_path: ""

ssl_cert_local_path: "../../files/certs/notsecure.crt"
ssl_cert_path: "/etc/pki/tls/certs/notsecure.crt"

ssl_key_local_path: "../../files/certs/notsecure.key"
ssl_key_path: "/etc/pki/tls/certs/notsecure.key"

proxy_pass_host: localhost
proxy_pass_port: 8080

server_auth_method: ""

nginx_log_dir: "/var/log/nginx"
nginx_error_log: "{{ nginx_log_dir }}/{{ nginx_vhost_filename }}-error.log"
nginx_access_log: "{{ nginx_log_dir }}/{{ nginx_vhost_filename}}-access.log"
